#!/usr/bin/python

import re
import io
import sys
import os 



def help():
    print(
        '''
getips

SYNOPSIS: 
    getips4 [OPTION] [FILE]

DESCRIPTION:
    Extracts IP Addresses v4 from a file.
    Matches the Regex \d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}

OPTION:
    -h, --help
        show the manual

    -r, --replace
        surrounds "dots" symbols with square brackets

        '''
    )
    exit(1)

def main():
    REGEX = "\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}"
    files = []
    ips = []
    replace = False

    # Parse arguments
    args = sys.argv
    for arg in args:
        if arg == args[0]:
            continue
        elif arg == "-h" or arg == "--help":
            help()
            continue
        elif arg == "-r" or arg == "--replace":
            replace = True
            continue
        else:
            files.append(arg) 

    # Parse file
    if files: 
        for file in files:
            if not os.path.exists(file):
                print("Error: " + file + " not found.")
            else:
                stream = io.open(
                    file,
                    mode = "r",
                    encoding = "utf-8",
                    errors = "surrogateescape")

                fileContent = stream.read()
                matches = re.findall(REGEX, fileContent)
                if matches:
                    for match in matches:
                        ips.append(match)
    else:
        print("Error: no input file given.")
        help()

    if ips:
        # Order and remove duplicates
        ips = list(set(ips))

        # Replace "." with "[.]"
        if replace == True:
            c = 0
            for url in ips:
                ips[c] = url.replace(".", "[.]")
                c =  c + 1
        for ip in ips:
            print(ip)
    else:
        print("Warning: no IP found.")

if __name__=="__main__":
    try:
        main()
    except KeyboardInterrupt:
        print('Warning: keyboard interrupt received')
