#!/bin/sh

function help() {

	echo '
gnome-help

SYNOPSIS: 
    gnome-help [OPTIONS]

OPTIONS:
    -h --help
        Show the manual
    -K --reset-keybindings
        Resets keybindings settings for Gnome to default values
    -k --set-keybindings
        Disables unused keybindings and sets basic "tiling windows manager"-like keybindings
    -g --get-keybindings
        Get current configuration for Gnome keybindings settings
    -i --refresh-icons
        Refresh current icon theme to apply changes
    -s --search-icons [PATTERN]
        Search all ".desktop" files matching given pattern
'
}

function _set() {
    gsettings set org.gnome.desktop.wm.keybindings close "['<Super>q']"
    gsettings set org.gnome.desktop.wm.keybindings minimize "['<Super>w']"
    gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-1 "['<Alt><Super>1']"
    gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-2 "['<Alt><Super>2']"
    gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-3 "['<Alt><Super>3']"
    gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-4 "['<Alt><Super>4']"
    gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-5 "['<Alt><Super>5']"
    gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-6 "['<Alt><Super>6']"
    gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-7 "['<Alt><Super>7']"
    gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-8 "['<Alt><Super>8']"
    gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-9 "['<Alt><Super>9']"
    gsettings set org.gnome.desktop.wm.keybindings switch-applications "['<Super>Tab']"
    gsettings set org.gnome.desktop.wm.keybindings switch-applications-backward "['<Shift><Super>Tab']"
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-1 "['<Super>1']"
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-2 "['<Super>2']"
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-3 "['<Super>3']"
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-4 "['<Super>4']"
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-5 "['<Super>5']"
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-6 "['<Super>6']"
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-7 "['<Super>7']"
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-8 "['<Super>8']"
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-9 "['<Super>9']"
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down "['']"
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "['<Super>Left']"
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "['<Super>Right']"
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up "['']"
    gsettings set org.gnome.desktop.wm.keybindings unmaximize "['']"
    # gsettings set org.gnome.mutter.keybindings toggle-tiled-left "['<Alt><Super>Left']"
    # gsettings set org.gnome.mutter.keybindings toggle-tiled-right "['<Alt><Super>Right']"
    gsettings set org.gnome.mutter.keybindings toggle-tiled-left "['']"
    gsettings set org.gnome.mutter.keybindings toggle-tiled-right "['']"
    gsettings set org.gnome.shell.keybindings shift-overview-down "['']"
    gsettings set org.gnome.shell.keybindings shift-overview-up "['']"
    gsettings set org.gnome.desktop.wm.keybindings activate-window-menu "['']"
    gsettings set org.gnome.desktop.wm.keybindings always-on-top "['']"
    gsettings set org.gnome.desktop.wm.keybindings begin-move "['']"
    gsettings set org.gnome.desktop.wm.keybindings begin-resize "['']"
    gsettings set org.gnome.desktop.wm.keybindings cycle-group "['']"
    gsettings set org.gnome.desktop.wm.keybindings cycle-group-backward "['']"
    gsettings set org.gnome.desktop.wm.keybindings cycle-panels "['']"
    gsettings set org.gnome.desktop.wm.keybindings cycle-panels-backward "['']"
    gsettings set org.gnome.desktop.wm.keybindings cycle-windows "['']"
    gsettings set org.gnome.desktop.wm.keybindings cycle-windows-backward "['']"
    gsettings set org.gnome.desktop.wm.keybindings lower "['']"
    gsettings set org.gnome.desktop.wm.keybindings maximize "['']"
    gsettings set org.gnome.desktop.wm.keybindings maximize-horizontally "['']"
    gsettings set org.gnome.desktop.wm.keybindings maximize-vertically "['']"
    gsettings set org.gnome.desktop.wm.keybindings move-to-center "['']"
    gsettings set org.gnome.desktop.wm.keybindings move-to-corner-ne "['']"
    gsettings set org.gnome.desktop.wm.keybindings move-to-corner-nw "['']"
    gsettings set org.gnome.desktop.wm.keybindings move-to-corner-se "['']"
    gsettings set org.gnome.desktop.wm.keybindings move-to-corner-sw "['']"
    gsettings set org.gnome.desktop.wm.keybindings move-to-monitor-down "['']"
    gsettings set org.gnome.desktop.wm.keybindings move-to-monitor-left "['']"
    gsettings set org.gnome.desktop.wm.keybindings move-to-monitor-right "['']"
    gsettings set org.gnome.desktop.wm.keybindings move-to-monitor-up "['']"
    gsettings set org.gnome.desktop.wm.keybindings move-to-side-e "['']"
    gsettings set org.gnome.desktop.wm.keybindings move-to-side-n "['']"
    gsettings set org.gnome.desktop.wm.keybindings move-to-side-s "['']"
    gsettings set org.gnome.desktop.wm.keybindings move-to-side-w "['']"
    gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-10 "['']"
    gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-11 "['']"
    gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-12 "['']"
    gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-down "['']"
    gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-last "['']"
    gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-left "['']"
    gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-right "['']"
    gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-up "['']"
    gsettings set org.gnome.desktop.wm.keybindings panel-main-menu "['']"
    gsettings set org.gnome.desktop.wm.keybindings panel-run-dialog "['']"
    gsettings set org.gnome.desktop.wm.keybindings raise "['']"
    gsettings set org.gnome.desktop.wm.keybindings raise-or-lower "['']"
    gsettings set org.gnome.desktop.wm.keybindings set-spew-mark "['']"
    gsettings set org.gnome.desktop.wm.keybindings show-desktop "['']"
    gsettings set org.gnome.desktop.wm.keybindings switch-group "['']"
    gsettings set org.gnome.desktop.wm.keybindings switch-group-backward "['']"
    gsettings set org.gnome.desktop.wm.keybindings switch-input-source "['']"
    gsettings set org.gnome.desktop.wm.keybindings switch-input-source-backward "['']"
    gsettings set org.gnome.desktop.wm.keybindings switch-panels "['']"
    gsettings set org.gnome.desktop.wm.keybindings switch-panels-backward "['']"
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-10 "['']"
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-11 "['']"
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-12 "['']"
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-last "['']"
    gsettings set org.gnome.desktop.wm.keybindings switch-windows "['']"
    gsettings set org.gnome.desktop.wm.keybindings switch-windows-backward "['']"
    gsettings set org.gnome.desktop.wm.keybindings toggle-above "['']"
    gsettings set org.gnome.desktop.wm.keybindings toggle-fullscreen "['']"
    # gsettings set org.gnome.desktop.wm.keybindings toggle-maximized "['<Super>M']"
    gsettings set org.gnome.desktop.wm.keybindings toggle-maximized "['']"
    gsettings set org.gnome.desktop.wm.keybindings toggle-on-all-workspaces "['']"
    gsettings set org.gnome.desktop.wm.keybindings toggle-shaded "['']"
    gsettings set org.gnome.mutter.keybindings rotate-monitor "['']"
    gsettings set org.gnome.mutter.keybindings switch-monitor "['']"
    gsettings set org.gnome.mutter.keybindings tab-popup-cancel "['']"
    gsettings set org.gnome.mutter.keybindings tab-popup-select "['']"
    gsettings set org.gnome.mutter.wayland.keybindings restore-shortcuts "['']"
    gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-1 "['']"
    gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-10 "['']"
    gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-11 "['']"
    gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-12 "['']"
    gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-2 "['']"
    gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-3 "['']"
    gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-4 "['']"
    gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-5 "['']"
    gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-6 "['']"
    gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-7 "['']"
    gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-8 "['']"
    gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-9 "['']"
    #gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['']"
    gsettings set org.gnome.shell.keybindings focus-active-notification "['']"
    gsettings set org.gnome.shell.keybindings open-application-menu "['']"
    gsettings set org.gnome.shell.keybindings switch-to-application-1 "['']"
    gsettings set org.gnome.shell.keybindings switch-to-application-2 "['']"
    gsettings set org.gnome.shell.keybindings switch-to-application-3 "['']"
    gsettings set org.gnome.shell.keybindings switch-to-application-4 "['']"
    gsettings set org.gnome.shell.keybindings switch-to-application-5 "['']"
    gsettings set org.gnome.shell.keybindings switch-to-application-6 "['']"
    gsettings set org.gnome.shell.keybindings switch-to-application-7 "['']"
    gsettings set org.gnome.shell.keybindings switch-to-application-8 "['']"
    gsettings set org.gnome.shell.keybindings switch-to-application-9 "['']"
    gsettings set org.gnome.shell.keybindings toggle-application-view "['']"
    gsettings set org.gnome.shell.keybindings toggle-message-tray "['']"
    gsettings set org.gnome.shell.keybindings toggle-overview "['']"
}

function _reset() {
    gsettings reset org.gnome.desktop.wm.keybindings close
    gsettings reset org.gnome.desktop.wm.keybindings minimize
    gsettings reset org.gnome.desktop.wm.keybindings move-to-workspace-1
    gsettings reset org.gnome.desktop.wm.keybindings move-to-workspace-2
    gsettings reset org.gnome.desktop.wm.keybindings move-to-workspace-3
    gsettings reset org.gnome.desktop.wm.keybindings move-to-workspace-4
    gsettings reset org.gnome.desktop.wm.keybindings move-to-workspace-5
    gsettings reset org.gnome.desktop.wm.keybindings move-to-workspace-6
    gsettings reset org.gnome.desktop.wm.keybindings move-to-workspace-7
    gsettings reset org.gnome.desktop.wm.keybindings move-to-workspace-8
    gsettings reset org.gnome.desktop.wm.keybindings move-to-workspace-9
    gsettings reset org.gnome.desktop.wm.keybindings switch-applications
    gsettings reset org.gnome.desktop.wm.keybindings switch-applications-backward
    gsettings reset org.gnome.desktop.wm.keybindings switch-to-workspace-1
    gsettings reset org.gnome.desktop.wm.keybindings switch-to-workspace-2
    gsettings reset org.gnome.desktop.wm.keybindings switch-to-workspace-3
    gsettings reset org.gnome.desktop.wm.keybindings switch-to-workspace-4
    gsettings reset org.gnome.desktop.wm.keybindings switch-to-workspace-5
    gsettings reset org.gnome.desktop.wm.keybindings switch-to-workspace-6
    gsettings reset org.gnome.desktop.wm.keybindings switch-to-workspace-7
    gsettings reset org.gnome.desktop.wm.keybindings switch-to-workspace-8
    gsettings reset org.gnome.desktop.wm.keybindings switch-to-workspace-9
    gsettings reset org.gnome.desktop.wm.keybindings switch-to-workspace-down
    gsettings reset org.gnome.desktop.wm.keybindings switch-to-workspace-left
    gsettings reset org.gnome.desktop.wm.keybindings switch-to-workspace-right
    gsettings reset org.gnome.desktop.wm.keybindings switch-to-workspace-up
    gsettings reset org.gnome.desktop.wm.keybindings unmaximize
    gsettings reset org.gnome.mutter.keybindings toggle-tiled-left
    gsettings reset org.gnome.mutter.keybindings toggle-tiled-right
    gsettings reset org.gnome.shell.keybindings shift-overview-down
    gsettings reset org.gnome.shell.keybindings shift-overview-up
    gsettings reset org.gnome.desktop.wm.keybindings activate-window-menu
    gsettings reset org.gnome.desktop.wm.keybindings always-on-top
    gsettings reset org.gnome.desktop.wm.keybindings begin-move
    gsettings reset org.gnome.desktop.wm.keybindings begin-resize
    gsettings reset org.gnome.desktop.wm.keybindings cycle-group
    gsettings reset org.gnome.desktop.wm.keybindings cycle-group-backward
    gsettings reset org.gnome.desktop.wm.keybindings cycle-panels
    gsettings reset org.gnome.desktop.wm.keybindings cycle-panels-backward
    gsettings reset org.gnome.desktop.wm.keybindings cycle-windows
    gsettings reset org.gnome.desktop.wm.keybindings cycle-windows-backward
    gsettings reset org.gnome.desktop.wm.keybindings lower
    gsettings reset org.gnome.desktop.wm.keybindings maximize
    gsettings reset org.gnome.desktop.wm.keybindings maximize-horizontally
    gsettings reset org.gnome.desktop.wm.keybindings maximize-vertically
    gsettings reset org.gnome.desktop.wm.keybindings move-to-center
    gsettings reset org.gnome.desktop.wm.keybindings move-to-corner-ne
    gsettings reset org.gnome.desktop.wm.keybindings move-to-corner-nw
    gsettings reset org.gnome.desktop.wm.keybindings move-to-corner-se
    gsettings reset org.gnome.desktop.wm.keybindings move-to-corner-sw
    gsettings reset org.gnome.desktop.wm.keybindings move-to-monitor-down
    gsettings reset org.gnome.desktop.wm.keybindings move-to-monitor-left
    gsettings reset org.gnome.desktop.wm.keybindings move-to-monitor-right
    gsettings reset org.gnome.desktop.wm.keybindings move-to-monitor-up
    gsettings reset org.gnome.desktop.wm.keybindings move-to-side-e
    gsettings reset org.gnome.desktop.wm.keybindings move-to-side-n
    gsettings reset org.gnome.desktop.wm.keybindings move-to-side-s
    gsettings reset org.gnome.desktop.wm.keybindings move-to-side-w
    gsettings reset org.gnome.desktop.wm.keybindings move-to-workspace-10
    gsettings reset org.gnome.desktop.wm.keybindings move-to-workspace-11
    gsettings reset org.gnome.desktop.wm.keybindings move-to-workspace-12
    gsettings reset org.gnome.desktop.wm.keybindings move-to-workspace-down
    gsettings reset org.gnome.desktop.wm.keybindings move-to-workspace-last
    gsettings reset org.gnome.desktop.wm.keybindings move-to-workspace-left
    gsettings reset org.gnome.desktop.wm.keybindings move-to-workspace-right
    gsettings reset org.gnome.desktop.wm.keybindings move-to-workspace-up
    gsettings reset org.gnome.desktop.wm.keybindings panel-main-menu
    gsettings reset org.gnome.desktop.wm.keybindings panel-run-dialog
    gsettings reset org.gnome.desktop.wm.keybindings raise
    gsettings reset org.gnome.desktop.wm.keybindings raise-or-lower
    gsettings reset org.gnome.desktop.wm.keybindings set-spew-mark
    gsettings reset org.gnome.desktop.wm.keybindings show-desktop
    gsettings reset org.gnome.desktop.wm.keybindings switch-group
    gsettings reset org.gnome.desktop.wm.keybindings switch-group-backward
    gsettings reset org.gnome.desktop.wm.keybindings switch-input-source
    gsettings reset org.gnome.desktop.wm.keybindings switch-input-source-backward
    gsettings reset org.gnome.desktop.wm.keybindings switch-panels
    gsettings reset org.gnome.desktop.wm.keybindings switch-panels-backward
    gsettings reset org.gnome.desktop.wm.keybindings switch-to-workspace-10
    gsettings reset org.gnome.desktop.wm.keybindings switch-to-workspace-11
    gsettings reset org.gnome.desktop.wm.keybindings switch-to-workspace-12
    gsettings reset org.gnome.desktop.wm.keybindings switch-to-workspace-last
    gsettings reset org.gnome.desktop.wm.keybindings switch-windows
    gsettings reset org.gnome.desktop.wm.keybindings switch-windows-backward
    gsettings reset org.gnome.desktop.wm.keybindings toggle-above
    gsettings reset org.gnome.desktop.wm.keybindings toggle-fullscreen
    gsettings reset org.gnome.desktop.wm.keybindings toggle-maximized
    gsettings reset org.gnome.desktop.wm.keybindings toggle-on-all-workspaces
    gsettings reset org.gnome.desktop.wm.keybindings toggle-shaded
    gsettings reset org.gnome.mutter.keybindings rotate-monitor
    gsettings reset org.gnome.mutter.keybindings switch-monitor
    gsettings reset org.gnome.mutter.keybindings tab-popup-cancel
    gsettings reset org.gnome.mutter.keybindings tab-popup-select
    gsettings reset org.gnome.mutter.wayland.keybindings restore-shortcuts
    gsettings reset org.gnome.mutter.wayland.keybindings switch-to-session-1
    gsettings reset org.gnome.mutter.wayland.keybindings switch-to-session-10
    gsettings reset org.gnome.mutter.wayland.keybindings switch-to-session-11
    gsettings reset org.gnome.mutter.wayland.keybindings switch-to-session-12
    gsettings reset org.gnome.mutter.wayland.keybindings switch-to-session-2
    gsettings reset org.gnome.mutter.wayland.keybindings switch-to-session-3
    gsettings reset org.gnome.mutter.wayland.keybindings switch-to-session-4
    gsettings reset org.gnome.mutter.wayland.keybindings switch-to-session-5
    gsettings reset org.gnome.mutter.wayland.keybindings switch-to-session-6
    gsettings reset org.gnome.mutter.wayland.keybindings switch-to-session-7
    gsettings reset org.gnome.mutter.wayland.keybindings switch-to-session-8
    gsettings reset org.gnome.mutter.wayland.keybindings switch-to-session-9
    #gsettings reset org.gnome.settings-daemon.plugins.media-keys custom-keybindings
    gsettings reset org.gnome.shell.keybindings focus-active-notification
    gsettings reset org.gnome.shell.keybindings open-application-menu
    gsettings reset org.gnome.shell.keybindings switch-to-application-1
    gsettings reset org.gnome.shell.keybindings switch-to-application-2
    gsettings reset org.gnome.shell.keybindings switch-to-application-3
    gsettings reset org.gnome.shell.keybindings switch-to-application-4
    gsettings reset org.gnome.shell.keybindings switch-to-application-5
    gsettings reset org.gnome.shell.keybindings switch-to-application-6
    gsettings reset org.gnome.shell.keybindings switch-to-application-7
    gsettings reset org.gnome.shell.keybindings switch-to-application-8
    gsettings reset org.gnome.shell.keybindings switch-to-application-9
    gsettings reset org.gnome.shell.keybindings toggle-application-view
    gsettings reset org.gnome.shell.keybindings toggle-message-tray
    gsettings reset org.gnome.shell.keybindings toggle-overview
}

function _get() {
    gsettings list-recursively | grep -E 'keybindings|media-keys' | sort
}

if [ -z "$1" ]; then
	echo "Error: no argument given"
	help
	exit 1
fi

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
	help
	exit 0
elif [ "$1" == "-K" ] || [ "$1" == "--reset-keybindings" ]; then
    _reset
    exit 0
elif [ "$1" == "-k" ] || [ "$1" == "--set-keybindings" ]; then
    _set
    exit 0
elif [ "$1" == "-g" ] || [ "$1" == "--get-keybindings" ]; then
    _get
    exit 0
elif [ "$1" == "-i" ] || [ "$1" == "--refresh-icons" ] ; then
	if command -v gsettings &> /dev/null; then
		iconTheme=$(gsettings get org.gnome.desktop.interface icon-theme)
		gsettings set org.gnome.desktop.interface icon-theme ""
		gsettings set org.gnome.desktop.interface icon-theme "$iconTheme"
	else
		echo "gsettings not found"
		exit 2
	fi
elif [ "$1" == "-s" ] || [ "$1" == "--search-icons" ]; then
	if [ -z "$2" ]; then
		echo "no pattern specified after -s, --search-icons!"
		help
		exit 22
	else
		sudo find /usr/share/applications/ -iname "*$2*.desktop" 2>/dev/null
	fi
fi
