#!/bin/sh

function help() {

        echo '
hex

SYNOPSIS:
        hex [CHAR]

DESCRIPTION:
        Print Hexadecimal value of given input.

EXAMPLES:
        hex \x27
        Output: \x0027

        hex a
        Output: \x0061


'
}

if [ -z "$1" ]; then
        echo "Error: no CHAR argument given"
        help
        exit 1
fi

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
        help
        exit 0
fi

if [ $(expr length $1) != "1" ]; then
	echo "Error: please insert just one char"
	exit 1
fi

echo \\x$(echo -n "$1" | hexdump | cut -c 9-)

exit 0
