#!/bin/bash

FILE_BRIGHTNESS="/sys/class/backlight/intel_backlight/brightness"
FILE_MAX_BRIGHTNESS="/sys/class/backlight/intel_backlight/max_brightness"

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
	echo '
scronf

Description:
	Set display backlight OFF if they are ON and viceversa.

Usage: scronf [OPTIONS]
	
Options:
	-h --help
		Show this help
'
    exit 0
fi

if grep -qE "^0$" $FILE_BRIGHTNESS; then
    sudo -- bash -c 'echo -n "Screen backlights ON with value "; cat '$FILE_MAX_BRIGHTNESS' | tee '"$FILE_BRIGHTNESS"
else
    sudo -- bash -c 'echo -n "Screen backlights OFF with value "; echo "0" | tee '"$FILE_BRIGHTNESS"
fi

exit 0
